<?php
/**
* @file
* This runs a weekly countdown to an hour called beer o'clock
*
* This contains all of the non-js code for the module
*
*/

/**
 * Implements hook_help().
 */
function beer_o_clock_help($path, $arg) {
  switch ($path) {
    case 'admin/help#beer_o_clock':
      return '<p>' . t("Provides an easy way to produce a page that will simply tell you whether it is beer o'clock yet or not. Beer o'clock can be configured in the administration settings for the site to suit your particular company/workplace.") . '</p>';
  }
}

/**
 * Implements hook_theme().
 */
function beer_o_clock_theme() {
  return array(
    'beer_o_clock_block' => array(
      'variables' => array('message' => NULL),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function beer_o_clock_menu() {
  $items = array();
  $items['admin/config/system/beer-o-clock'] = array(
    'page callback'     => 'drupal_get_form',
    'page arguments'    => array('beer_o_clock_settings'),
    'title'             => "Beer O'Clock Settings",
    'description'       => "Configure when it is time for Beer O'Clock",
    'type'              => MENU_NORMAL_ITEM,
    'access arguments'  => array('access administration pages')
  );
  $items['admin/reports/is_it_beer_o_clock'] = array(
    'page callback'     => 'beer_o_clock_check',
    'title'             => "Is it Beer O'Clock yet?",
    'description'       => "Check to see if it is time for Beer O'Clock now",
    'type'              => MENU_NORMAL_ITEM,
    'access arguments'  => array('access administration pages'),
  );
  return $items;
}

/**
 * The administration settings form
 */
function beer_o_clock_settings($form, $form_state) {
  // sunday is day zero to co-incide with PHP.net
  $form['beer_o_clock_day'] = array(
    '#type'          => 'select',
    '#title'         => "Beer O'Clock Day of the week",
    '#description'   => "The day on which Beer O'Clock is on",
    '#options'       => array(
      0 => t('Sunday'),
      1 => t('Monday'),
      2 => t('Tuesday'),
      3 => t('Wednesday'),
      4 => t('Thursday'),
      5 => t('Friday'),
      6 => t('Saturday'),
    ),
    '#default_value' => variable_get('beer_o_clock_day', 5),
    '#required'      => TRUE,
  );
  $form['beer_o_clock_hour'] = array(
    '#type'          => 'select',
    '#title'         => t("Beer O'Clock Hour of the day"),
    '#description'   => t("The time that Beer O'Clock starts - in 24 hour time format"),
    '#options'       => range(0, 23),
    '#default_value' => variable_get('beer_o_clock_hour', 16),
    '#required'      => TRUE,
  );
  $form['beer_o_clock_message'] = array(
    '#title'         => t("Message to display when it is Beer O'Clock"),
    '#type'          => 'textarea',
    '#description'   => t("You can use most common HTML tags"),
    '#default_value' => variable_get('beer_o_clock_message', t('It sure is!')),
  );
  $form['beer_o_clock_not_message'] = array(
    '#title'         => t("Message to display when it is not Beer O'Clock"),
    '#type'          => 'textarea',
    '#description'   => t("You can use most common HTML tags"),
    '#default_value' => variable_get('beer_o_clock_not_message', t('Not yet buddy!')),
  );

  $form['#validate'][] = 'beer_o_clock_settings_validate';
  return system_settings_form($form);
}

/**
 * Unused validation callback for the administration settings, could potentially
 * be used in the future to make sure sensible settings are used.
 */
function beer_o_clock_settings_validate($form, $form_state) {
}

/**
 * Page callback
 */
function beer_o_clock_check() {
  $beer_day = variable_get('beer_o_clock_day', 5);
  $beer_hour = variable_get('beer_o_clock_hour', 16);
  $mess = variable_get('beer_o_clock_message', t("It sure isn't"));
  $today = date('w');
  $hour = date('G');
  if ($beer_day == $today && $hour == $beer_hour) {
    $output = theme('beer_o_clock_block', array('message' => variable_get('beer_o_clock_message', t('It sure is!'))));
  }
  else{
    if (variable_get('display_boc_countdown', TRUE)) {
     $boc = new DateTime();
     if ($beer_day != $today) {
        if ($beer_day < $today) {
          //makes today negative number
          $today = $beer_day - $today;
        }
         //ternary if it is more than one it is day day is days other wise
         (($beer_day - $today) == 1) ? $day = "day" : $day = "days";
        //finds number of days till beer o'clock (if negative it effectively
       //becomes addition
       $diff = $beer_day - $today;
       //increase change beer o'clock to be the next friday
       $boc->modify("+" . $diff . " " . $day);
     }
     else {

      if ($beer_hour <= $hour) {
        $boc->modify("+7 days");
      }

     }
    //change beer o'clock to be correct hour
    $boc->setTime($beer_hour, 0, 0);
    $boc_timer = $boc->format('U');
    $boc_timer = (int)$boc_timer;
    drupal_add_js(array('beer_o_clock' => array('boc_timer' => $boc_timer)), 'setting');
    drupal_add_js(array('beer_o_clock' => array('boc_mess' => $mess)), 'setting');
    }
    $output = theme('beer_o_clock_block', array('message' => variable_get('beer_o_clock_not_message', t('Not yet buddy!'))));
    if (variable_get('display_boc_countdown', TRUE)) {
      drupal_add_js('sites/all/modules/beer_o_clock/countdown.js');
    }
  }

  return '<p align ="center">' . $output . '</p>';
}

function theme_beer_o_clock_block($variables) {
    return "<div id='boc_text' align='center'>" . filter_xss_admin($variables['message']) . "</div>" . "<BR/> <div align='center' id= 'boc_timer'> </div>";
}

/**
 * Implements hook_block_info()
 **/
function beer_o_clock_block_info() {
  $blocks['beer_o_clock'] = array(
    'info'   => t('Beer O\'Clock'),
   'cache'  => DRUPAL_CACHE_GLOBAL,
  );
  return $blocks;
}
/**
 * Implements hook_block_view()
 **/
function beer_o_clock_block_view($delta = '') {
  switch ($delta) {
    case'beer_o_clock':
      $block['subject'] = t("Is it Beer O'Clock?");
      if (user_access('access_beer_o_clock')) {
        $block['content'] = beer_o_clock_check();
      }
      break;
  }
  return $block;
}
/**
 * Implements hook_permission()
 **/
function beer_o_clock_permission() {
  return array(
    'access_beer_o_clock' => array(
      'title' => t('Access Beer O\'Clock'),
      'description' => t('ability to view Beer O\'Clock stuff'),
    ),
  );
}

/**
 * Implements hook_block_configure()
 **/
function beer_o_clock_block_configure($delta = '') {
  $form = array();
  if ($delta == "beer_o_clock") {
    $form['display_boc_countdown'] = array(
      '#type' => 'checkbox',
      '#title' => "Display the countdown to Beer O'Clock",
      '#default_value' => variable_get('display_boc_countdown', TRUE),
    );
  }
  return $form;
}
/**
 * Implements hook_block_save()
 **/
function beer_o_clock_block_save($delta = '', $edit = array()) {
  if ($delta == 'beer_o_clock') {
    variable_set('display_boc_countdown', $edit['display_boc_countdown']);
  }
}
