<?php

/**
 * @file
 * This runs a weekly countdown to an hour called beer o'clock.
 */

/**
 * Implements hook_menu().
 */
function beer_o_clock_menu() {
  $items = array();
  $items['admin/config/system/beer-o-clock'] = array(
    'title' => "Beer O'Clock Settings",
    'description' => "Configure when it is time for Beer O'Clock",
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('beer_o_clock_settings'),
    'access arguments' => array('administer site configuration'),
    'file' => 'beer_o_clock.admin.inc',
  );
  $items['admin/reports/is_it_beer_o_clock'] = array(
    'title' => "Is it Beer O'Clock yet?",
    'description' => "Check to see if it is time for Beer O'Clock now",
    'page callback' => 'beer_o_clock_check',
    'access arguments' => array('access administration pages'),
  );
  return $items;
}

/**
 * Implements hook_theme().
 */
function beer_o_clock_theme() {
  return array(
    'beer_o_clock_block' => array(
      'variables' => array('message' => NULL),
    ),
  );
}

/**
 * Implements hook_config_info().
 */
function beer_o_clock_config_info() {
  $configs = array();
  $configs['beer_o_clock.settings'] = array(
    'label' => t('Beer O\'Clock settings'),
  );
  return $configs;
}

/**
 * Page callback.
 */
function beer_o_clock_check() {
  $config = config('beer_o_clock.settings');
  $beer_day = $config->get('beer_o_clock_day');
  $beer_hour = $config->get('beer_o_clock_hour');
  $beer_countdown_displayed = (bool) $config->get('beer_o_clock_block_countdown');
  $today = date('w');
  $hour = date('G');

  // Test to see if it is Beer O'Clock now.
  if ($beer_day == $today && $hour == $beer_hour) {
    $output = theme('beer_o_clock_block', array(
      'message' => $config->get('beer_o_clock_message'),
    ));
  }
  // Not Beer O'Clock, additional logic is required to work out when it is next.
  else if ($beer_countdown_displayed) {
    $boc = new DateTime();
    if ($beer_day != $today) {
      if ($beer_day < $today) {
        // Makes today negative number.
        $today = $beer_day - $today;
      }
      // If it is more than one it is day day is days otherwise.
      (($beer_day - $today) == 1) ? $day = "day" : $day = "days";
      // Finds number of days till beer o'clock (if negative it effectively.
      // becomes addition.
      $diff = $beer_day - $today;
      // Increase change beer o'clock to be the next Friday.
      $boc->modify("+" . $diff . " " . $day);
    } else {
      if ($beer_hour <= $hour) {
        $boc->modify("+7 days");
      }
    }

    // Change beer o'clock to be correct hour.
    $boc->setTime($beer_hour, 0, 0);

    backdrop_add_js(array('beer_o_clock' => array(
      'boc_timer' => (int) $boc->format('U'),
      'boc_mess' => $config->get('beer_o_clock_message'),
    )), 'setting');

    $output = theme('beer_o_clock_block', array(
      'message' => $config->get('beer_o_clock_not_message'),
    ));
    backdrop_add_js(backdrop_get_path('module', 'beer_o_clock') . '/countdown.js');
  }
  // Not Beer O'Clock, no countdown required.
  else {
    $output = theme('beer_o_clock_block', array(
      'message' => $config->get('beer_o_clock_not_message'),
    ));
  }

  return '<p align ="center">' . $output . '</p>';
}

/**
 * Theme function for the Beer O'Clock block.
 *
 * @todo convert to a template.
 */
function theme_beer_o_clock_block($variables) {
  return "<div id='boc_text'>" .
    filter_xss_admin($variables['message']) .
    "</div>" .
    "<div id='boc_timer'></div>";
}

/**
 * Implements hook_block_info().
 */
function beer_o_clock_block_info() {
  $blocks['beer_o_clock'] = array(
    'info' => t("Beer O'Clock"),
    'cache' => BACKDROP_CACHE_GLOBAL,
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function beer_o_clock_block_view($delta = '') {
  switch ($delta) {
    case 'beer_o_clock':
      $block['subject'] = t("Is it Beer O'Clock?");
      $block['content'] = beer_o_clock_check();
      break;
  }

  return $block;
}

